---
title: "bootstrapped diy k-fold"
author: "Leah Boger"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load data
```{r}
require("mpath")
library("plotrix")
require("zic")
require("pscl")
library("purrr")
library("caret")
library("tidyverse")
data(docvisits)
```

#Create Interaction Covariates
```{r}
dt <- docvisits[,-(2:3)]
tmp <- model.matrix(~age30*health+age35*health+age40*health+age45*health+age50*health
+age55*health+age60*health, data=dt)[,-(1:9)]
dat <- cbind(dt, tmp)
```

#histigram of data
```{r}
barplot(with(docvisits,table(docvisits)),ylab="Frequency",xlab="Doctor office visits")
```



#look at null Model
```{r}


m1 <- zeroinfl(docvisits~.|., data=dat)


summary(m1)
cat("loglik of zero-inflated model", logLik(m1))
cat("BIC of zero-inflated model", AIC(m1, k=log(dim(dat)[1])))
AIC(m1)
```

#Use backwackward stepwise variable elimination to fit model

```{r}
fitbe <- be.zeroinfl(m1, data=dat, alpha=0.01, trace=FALSE)
summary(fitbe)
cat("loglik of zero-inflated model with backward selection",logLik(fitbe))
cat("BIC of zero-inflated model with backward selection", AIC(fitbe,k=log(dim(dat)[1])))
AIC(fitbe)
#AIC is lower than null model indicating a better fit


#backwards_mod <- zeroinfl(docvisits ~ health + handicap + married + children + self + civil + age45 + age55 + age60 + health*age45 + health*age55 + health*age60| health + age50 , data = dat)
```





**Bootstrapped not stratified for backward stepwise variable selected model with 250 iterations**
```{r}
boot_ns_kfold <- function(i){
  dat_kfold <- caret::createFolds(dat[["docvisits"]], k = 10, list = TRUE)
  # Use the list of row-indices to create data.frames for each fold
  dat_kdf <- purrr::map_dfr(dat_kfold, ~dat[.x,], .id = "Fold")
  k <- 1:10
  cv_function <- function(i) {
  fold_num <- sprintf("Fold%02d", i)  # Create fold name with leading zero if necessary
   Training_min1wf <- dat_kdf %>% filter(Fold != fold_num)
  Training_min1 <- Training_min1wf[-(1:1)]
  Test_1wf <- dat_kdf %>% filter(Fold == fold_num)
  Test_1 <- Test_1wf[-(1:1)]
  fold_mod <- zeroinfl(docvisits ~ health + handicap + married + children + self + civil + age45 + age55 + age60 + health*age45 + health*age55 + health*age60| health + age50, data = Training_min1)
  pred <- predict(fold_mod, newdata = Test_1)
  squared_dif <- (pred - Test_1$docvisits)^2
  mse <- mean(squared_dif)
  #rmse <- sqrt(mse) 
  aic <- AIC(fold_mod)
  return(list(AIC = aic, MSE = mse))
}

# Run the function for each fold
fold_mse <- as.data.frame(t(as.data.frame(sapply(k, cv_function))))

fold_mse$AIC <- as.numeric(fold_mse$AIC)
fold_mse$MSE <- as.numeric(fold_mse$MSE)


null_avgAIC <- mean(fold_mse$AIC)
null_avgMSE <- mean(fold_mse$MSE)

RMSE <- sqrt(null_avgMSE)
return(list(null_avgAIC, RMSE))
}


result_ns <- purrr::map_dfr(1:250, function(i) {
  res <- boot_ns_kfold(i)
  list(null_avgAIC = res[[1]], RMSE = res[[2]])
})

result_ns <- as.data.frame(result_ns)
AIC_ns <- mean(result_ns$null_avgAIC)
RMSE_ns <- mean(result_ns$RMSE)
stnd_error_mean_ns <- sd(result_ns$null_avgAIC)/ sqrt(length(result_ns))
stnd_error_rmse_ns <- sd(result_ns$RMSE)/ sqrt(length(result_ns))
```

**stratified bootstrap with backwards variable selected model using 250 iterations**
```{r}
boot_s_kfold <- function(i){
  #create logical variable on if docvisits is = 0
  dat_log <- dat %>% mutate(docvisits_cat = ifelse(docvisits ==0, TRUE, FALSE))
  #create fold indices
  dat_stratkfold <- createFolds(dat_log[["docvisits_cat"]], k = 10, list = TRUE)
  # Use the list of row-indices to create data.frames for each fold
  dat_stratkdf <- purrr::map_dfr(dat_stratkfold, ~dat_log[.x,], .id = "Fold") %>% select(-docvisits_cat)


  k <- 1:10
  cv_function_strat <- function(i) {
  fold_num <- sprintf("Fold%02d", i)  # Create fold name with leading zero if necessary
  
  Training_min1wf_strat <- dat_stratkdf %>% filter(Fold != fold_num)
  Training_min1_strat <- Training_min1wf_strat[-(1:1)]
  
  Test_1wf_strat <- dat_stratkdf %>% filter(Fold == fold_num)
  Test_1_strat <- Test_1wf_strat[-(1:1)]
  
  fold_mod_strat <- zeroinfl(docvisits ~ health + handicap + married + children + self + civil + age45 + age55 + age60 + health*age45 + health*age55 + health*age60| health + age50, data = Training_min1_strat)
  
  pred_strat <- predict(fold_mod_strat, newdata = Test_1_strat)
  
  squared_dif_strat <- (pred_strat - Test_1_strat$docvisits)^2
  
  mse_strat <- mean(squared_dif_strat)
  
  #rmse_strat <- sqrt(mse_strat)
  AIC_strat <- AIC(fold_mod_strat)
  
  return(list(AIC_s = AIC_strat, MSE_s = mse_strat))
  
}

fold_mse_strat <- as.data.frame(t(as.data.frame(sapply(k, cv_function_strat))))

fold_mse_strat$AIC_s <- as.numeric(fold_mse_strat$AIC_s)
fold_mse_strat$MSE_s <- as.numeric(fold_mse_strat$MSE_s)

null_avg_strat_AIC <- mean(fold_mse_strat$AIC_s)
null_avg_strat_MSE <- mean(fold_mse_strat$MSE_s)

RMSE_strat <- sqrt(null_avg_strat_MSE)

return(list(null_avg_strat_AIC, RMSE_strat))

}


result_s <- map_dfr(1:250, function(i) {
  res <- boot_s_kfold(i)
  list(null_avg_strat_AIC = res[[1]], RMSE_strat = res[[2]])
})

result_s <- as.data.frame(result_s)

AIC_s <- mean(result_s$null_avg_strat_AIC)
RMSE_s <- mean(result_s$RMSE_strat)
stnd_error_mean_s <- sd(result_s$null_avg_strat_AIC)/ sqrt(length(result_s))
stnd_error_rmse_s <- sd(result_s$RMSE_strat)/ sqrt(length(result_s))
```


**Compare MSE**
```{r}

F <- RMSE_ns / RMSE_s


pval <- pf(F, 249, 249, lower.tail = FALSE)

pval

#pval > 0.05 so we fail to reject null hypothesis(null hypothesis is that the both RMSE are equal)
```

